import { createClient } from "@supabase/supabase-js";
import dotenv from "dotenv";

dotenv.config();

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("錯誤：找不到 Supabase URL 或 ANON KEY，請確認根目錄的 .env 檔案存在且內容正確。");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const newBooks = [
  {
    title: "Operating System Concepts, 10th Edition (恐龍書)",
    author: "Abraham Silberschatz, Peter B. Galvin",
    edition: "10th Edition",
    price: 520,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Computer Science",
    school: "National Taiwan University",
    professor: "薛智恒 教授",
    location: "台大資工系館 / 德田館門口",
    cover_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
    owner_id: "owner-cs01",
    owner_name: "林冠宇",
    owner_avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCG8jM-azr1sxrBx_5pVjKMCusHCXpDw8xRa6v8J6p1TYGehT2m7MuL3rWDM0dsJDuWYja2KW2tfKuHSsHivmHsFRuzSObXbZkAAV3sAGzz1xewQckHIMw6e5mVQJhtu4htrQuNKtUWSmuxhPanuaSCs4g-DTq5p-WffAe0ZlPy79Abwf2DcclGEnw8T0-dj3uV3G378Ejq9styzfIaBoQMr3d1I9ZwCz_80ERjfhbyY03kPHcNGPFMLZKhYr1UY6E-XBEG7F4RnEw",
    owner_rating: 4.8,
    owner_trust_badges: ["誠信書主", "快速面交"],
    course_name: "作業系統 (Operating Systems)",
    course_professor: "薛智恒",
    course_department: "資訊工程學系",
    course_semester: "114-1"
  },
  {
    title: "Computer Organization and Design: MIPS Edition (算盤書)",
    author: "David A. Patterson, John L. Hennessy",
    edition: "5th Edition",
    price: 480,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Computer Science",
    school: "National Taiwan University",
    professor: "雷欽隆 教授",
    location: "台大正門 / 誠品公館店",
    cover_url: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
    owner_id: "owner-cs02",
    owner_name: "張品妤",
    owner_avatar_url: "https://lh3.googleusercontent.com/aida-public/AB6AXuCvSAcGKcNCqPxgQNQfUnI-p49nqH9w7aETJ90vhDL6qJ31a9AuLQZlHR4-pCP0gAUB2wPfTJ-VIHQS4XO288dF9RCoXnB-aLjjR0LD3Anc-8PNnVTj2tlxJ5WSWRlvcLkKbCJrzjhn62R-RMRfrJU25wE9CefFuvaV-3lilsZjdKQ4YLj_GmAQjtidjPvxRBnCMVsdBvMJc1ypsuKKlkzKE4RNGOprOHGMWXra4rE2aMNom0TW4tYh2FyBL8kY1iTldpxSWP0x6jA",
    owner_rating: 4.9,
    owner_trust_badges: ["優質書主"],
    course_name: "計算機組織 (Computer Organization)",
    course_professor: "雷欽隆",
    course_department: "資訊工程學系",
    course_semester: "114-1"
  },
  {
    title: "Macroeconomics (總體經濟學)",
    author: "N. Gregory Mankiw",
    edition: "9th Edition",
    price: 450,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Economics",
    school: "National Chengchi University",
    professor: "李學政 教授",
    location: "政大綜合大樓 / 麥側門口",
    cover_url: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400",
    owner_id: "owner-eco01",
    owner_name: "陳子晴",
    owner_avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    owner_rating: 4.7,
    owner_trust_badges: ["包裝完整"],
    course_name: "總體經濟學",
    course_professor: "李學政",
    course_department: "經濟學系",
    course_semester: "114-1"
  },
  {
    title: "Microeconomics (個體經濟學)",
    author: "Robert Pindyck, Daniel Rubinfeld",
    edition: "8th Edition",
    price: 400,
    condition: "Fair",
    tags: ["Fair"],
    department: "Economics",
    school: "National Chengchi University",
    professor: "王怡婷 教授",
    location: "政大商學院大門 / 社科院",
    cover_url: "https://images.unsplash.com/photo-1614028674026-a65e31bfd27c?w=400",
    owner_id: "owner-eco02",
    owner_name: "黃柏翰",
    owner_avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    owner_rating: 4.5,
    owner_trust_badges: [],
    course_name: "個體經濟學",
    course_professor: "王怡婷",
    course_department: "經濟學系",
    course_semester: "113-2"
  },
  {
    title: "Microelectronic Circuits (微電子電路 - 電子學聖經)",
    author: "Adel S. Sedra, Kenneth C. Smith",
    edition: "7th Edition",
    price: 550,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Electrical Engineering",
    school: "National Taiwan University",
    professor: "劉深淵 教授",
    location: "台大博雅教學館 / 明達館",
    cover_url: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400",
    owner_id: "owner-ee01",
    owner_name: "蔡睿恩",
    owner_avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    owner_rating: 5.0,
    owner_trust_badges: ["誠信書主", "回覆迅速"],
    course_name: "電子學 (Electronics)",
    course_professor: "劉深淵",
    course_department: "電機工程學系",
    course_semester: "114-1"
  },
  {
    title: "Fundamentals of Electric Circuits (電路學)",
    author: "Charles Alexander, Matthew Sadiku",
    edition: "6th Edition",
    price: 490,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Electrical Engineering",
    school: "National Taiwan University",
    professor: "李琳 教授",
    location: "台大二號館 / 電機一館",
    cover_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400",
    owner_id: "owner-ee02",
    owner_name: "許欣妤",
    owner_avatar_url: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    owner_rating: 4.6,
    owner_trust_badges: ["好溝通"],
    course_name: "電路學 (Electric Circuits)",
    course_professor: "李琳",
    course_department: "電機工程學系",
    course_semester: "114-1"
  },
  {
    title: "Calculus: Early Transcendentals (微積分)",
    author: "James Stewart",
    edition: "8th Edition",
    price: null,
    condition: "Fair",
    tags: ["Donation", "Fair"],
    department: "Computer Science",
    school: "Soochow University",
    professor: "張志明 教授",
    location: "東吳外雙溪校區 / 臨溪路公車站",
    cover_url: "https://images.unsplash.com/photo-1606326608606-aa0b62935f2b?w=400",
    owner_id: "owner-sz01",
    owner_name: "劉宇軒",
    owner_avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100",
    owner_rating: 4.7,
    owner_trust_badges: ["熱心贈書"],
    course_name: "微積分甲",
    course_professor: "張志明",
    course_department: "資訊科學系",
    course_semester: "113-1"
  },
  {
    title: "Java How to Program (Java 程式設計入門)",
    author: "Paul Deitel, Harvey Deitel",
    edition: "11th Edition",
    price: 380,
    condition: "Good",
    tags: ["Good"],
    department: "Computer Science",
    school: "Soochow University",
    professor: "李偉 教授",
    location: "東吳城中校區 / 捷運西門站 3 號出口",
    cover_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400",
    owner_id: "owner-sz02",
    owner_name: "陳宥廷",
    owner_avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100",
    owner_rating: 4.8,
    owner_trust_badges: [],
    course_name: "物件導向程式設計",
    course_professor: "李偉",
    course_department: "資訊科學系",
    course_semester: "114-1"
  },
  {
    title: "Introduction to Art (藝術概論)",
    author: "Rita Gilbert",
    edition: "5th Edition",
    price: 320,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Literature & Arts",
    school: "Fu Jen Catholic University",
    professor: "林麗華 教授",
    location: "輔仁大學藝術學院 / 捷運輔大站 1 號出口",
    cover_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
    owner_id: "owner-fj01",
    owner_name: "王思涵",
    owner_avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
    owner_rating: 4.9,
    owner_trust_badges: ["快速面交"],
    course_name: "藝術概論",
    course_professor: "林麗華",
    course_department: "應用美術學系",
    course_semester: "114-1"
  },
  {
    title: "A History of Western Music (西方音樂史)",
    author: "J. Peter Burkholder",
    edition: "9th Edition",
    price: 450,
    condition: "Good",
    tags: ["Good"],
    department: "Literature & Arts",
    school: "Fu Jen Catholic University",
    professor: "黃明 教授",
    location: "輔大真善美聖廣場 / 聖言樓",
    cover_url: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=400",
    owner_id: "owner-fj02",
    owner_name: "趙家豪",
    owner_avatar_url: "https://images.unsplash.com/photo-1542206395-9feb3edaa68d?w=100",
    owner_rating: 4.4,
    owner_trust_badges: [],
    course_name: "西方音樂史",
    course_professor: "黃明",
    course_department: "音樂學系",
    course_semester: "114-1"
  },
  {
    title: "Principles of Marketing (行銷學原理)",
    author: "Philip Kotler, Gary Armstrong",
    edition: "17th Edition",
    price: 400,
    condition: "Good",
    tags: ["Good"],
    department: "Economics",
    school: "National Chengchi University",
    professor: "張威廉 教授",
    location: "政大百年樓 / 逸仙樓",
    cover_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400",
    owner_id: "owner-mg01",
    owner_name: "李庭安",
    owner_avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    owner_rating: 4.6,
    owner_trust_badges: [],
    course_name: "行銷管理",
    course_professor: "張威廉",
    course_department: "企業管理學系",
    course_semester: "114-1"
  },
  {
    title: "Corporate Finance (財務管理 - 羅斯財管)",
    author: "Stephen Ross, Randolph Westerfield",
    edition: "11th Edition",
    price: 500,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Economics",
    school: "National Chengchi University",
    professor: "陳美華 教授",
    location: "政大達賢圖書館 / 捷運動物園站",
    cover_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=400",
    owner_id: "owner-mg02",
    owner_name: "高志明",
    owner_avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
    owner_rating: 4.8,
    owner_trust_badges: ["誠信書主"],
    course_name: "財務管理",
    course_professor: "陳美華",
    course_department: "金融學系",
    course_semester: "114-1"
  },
  {
    title: "Compilers: Principles, Techniques, and Tools (編譯器 - 龍書)",
    author: "Alfred V. Aho, Monica S. Lam",
    edition: "2nd Edition",
    price: 600,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Computer Science",
    school: "National Taiwan University",
    professor: "李政道 教授",
    location: "台大醉月湖畔 / 辛亥路後門",
    cover_url: "https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?w=400",
    owner_id: "owner-cs03",
    owner_name: "吳宗翰",
    owner_avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    owner_rating: 4.7,
    owner_trust_badges: ["好溝通"],
    course_name: "編譯器設計",
    course_professor: "李政道",
    course_department: "資訊工程學系",
    course_semester: "113-2"
  },
  {
    title: "Computer Networking: A Top-Down Approach (計算機網路)",
    author: "James F. Kurose, Keith W. Ross",
    edition: "7th Edition",
    price: 430,
    condition: "Fair",
    tags: ["Fair"],
    department: "Computer Science",
    school: "National Taiwan University",
    professor: "周承德 教授",
    location: "台大水源校區 / 捷運公館站 4 號出口",
    cover_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    owner_id: "owner-cs04",
    owner_name: "謝家瑜",
    owner_avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
    owner_rating: 4.5,
    owner_trust_badges: [],
    course_name: "計算機網路",
    course_professor: "周承德",
    course_department: "資訊工程學系",
    course_semester: "114-1"
  },
  {
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    edition: "3rd Edition",
    price: 650,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Computer Science",
    school: "National Taiwan University",
    professor: "林軒田 教授",
    location: "台大科教大樓 / 德田館 R103",
    cover_url: "https://images.unsplash.com/photo-1507146426996-ef05306b995a?w=400",
    owner_id: "owner-cs05",
    owner_name: "廖柏元",
    owner_avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100",
    owner_rating: 4.9,
    owner_trust_badges: ["誠信書主", "快速面交"],
    course_name: "人工智慧導論",
    course_professor: "林軒田",
    course_department: "資訊工程學系",
    course_semester: "114-1"
  },
  {
    title: "Discrete Mathematics and Its Applications (離散數學)",
    author: "Kenneth H. Rosen",
    edition: "8th Edition",
    price: 450,
    condition: "Good",
    tags: ["Good"],
    department: "Computer Science",
    school: "Soochow University",
    professor: "周佳穎 教授",
    location: "東吳雙溪第一教研大樓 / 閱覽室",
    cover_url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400",
    owner_id: "owner-sz03",
    owner_name: "徐雨婷",
    owner_avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    owner_rating: 4.6,
    owner_trust_badges: [],
    course_name: "離散數學",
    course_professor: "周佳穎",
    course_department: "資訊科學系",
    course_semester: "114-1"
  },
  {
    title: "Database System Concepts (資料庫系統概念)",
    author: "Abraham Silberschatz, Henry F. Korth",
    edition: "6th Edition",
    price: 480,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Computer Science",
    school: "Soochow University",
    professor: "陳柏翰 教授",
    location: "東吳城中大樓 R2102 / 西門",
    cover_url: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400",
    owner_id: "owner-sz04",
    owner_name: "葉承翰",
    owner_avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
    owner_rating: 4.8,
    owner_trust_badges: ["誠信書主"],
    course_name: "資料庫系統",
    course_professor: "陳柏翰",
    course_department: "資訊科學系",
    course_semester: "114-1"
  },
  {
    title: "Introduction to Algorithms, 3rd Edition (演算法導論白皮書)",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    edition: "3rd Edition",
    price: 500,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Computer Science",
    school: "Fu Jen Catholic University",
    professor: "李信利 教授",
    location: "輔大聖言樓 / 理工圖書館",
    cover_url: "https://images.unsplash.com/photo-1496181130204-7552cc14ac1a?w=400",
    owner_id: "owner-fj03",
    owner_name: "潘瑞恩",
    owner_avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100",
    owner_rating: 4.7,
    owner_trust_badges: ["優質書主"],
    course_name: "演算法設計與分析",
    course_professor: "李信利",
    course_department: "資訊工程學系",
    course_semester: "114-1"
  },
  {
    title: "Software Engineering: A Practitioner's Approach (軟體工程)",
    author: "Roger S. Pressman",
    edition: "8th Edition",
    price: null,
    condition: "Old",
    tags: ["Donation", "Old"],
    department: "Computer Science",
    school: "Fu Jen Catholic University",
    professor: "曾文賢 教授",
    location: "輔大羅耀拉大樓 / 外語學院",
    cover_url: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400",
    owner_id: "owner-fj04",
    owner_name: "廖品筑",
    owner_avatar_url: "https://images.unsplash.com/photo-1542206395-9feb3edaa68d?w=100",
    owner_rating: 4.9,
    owner_trust_badges: ["慷慨贈送"],
    course_name: "軟體工程系統設計",
    course_professor: "曾文賢",
    course_department: "資訊工程學系",
    course_semester: "113-2"
  },
  {
    title: "Introduction to Theory of Computation (計算理論導論)",
    author: "Michael Sipser",
    edition: "3rd Edition",
    price: 450,
    condition: "Good",
    tags: ["Good"],
    department: "Computer Science",
    school: "National Chengchi University",
    professor: "沈育民 教授",
    location: "政大理學院 / 達賢圖書館",
    cover_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400",
    owner_id: "owner-nccu03",
    owner_name: "沈冠廷",
    owner_avatar_url: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=100",
    owner_rating: 4.4,
    owner_trust_badges: [],
    course_name: "計算理論",
    course_professor: "沈育民",
    course_department: "資訊科學系",
    course_semester: "114-1"
  },
  {
    title: "Signals and Systems (信號與系統)",
    author: "Alan V. Oppenheim, Alan S. Willsky",
    edition: "2nd Edition",
    price: 520,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Electrical Engineering",
    school: "National Taiwan University",
    professor: "馮世邁 教授",
    location: "台大電機二館 / 舟山路路口",
    cover_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400",
    owner_id: "owner-ee03",
    owner_name: "簡廷儒",
    owner_avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    owner_rating: 4.8,
    owner_trust_badges: ["誠信書主"],
    course_name: "信號與系統",
    course_professor: "馮世邁",
    course_department: "電機工程學系",
    course_semester: "114-1"
  },
  {
    title: "Electromagnetics (電磁學原理)",
    author: "David K. Cheng",
    edition: "2nd Edition",
    price: 490,
    condition: "Fair",
    tags: ["Fair"],
    department: "Electrical Engineering",
    school: "National Taiwan University",
    professor: "江簡富 教授",
    location: "台大二號館 / 大一女舍旁",
    cover_url: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=400",
    owner_id: "owner-ee04",
    owner_name: "林佳蓉",
    owner_avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
    owner_rating: 4.6,
    owner_trust_badges: [],
    course_name: "電磁學二",
    course_professor: "江簡富",
    course_department: "電機工程學系",
    course_semester: "113-2"
  },
  {
    title: "Probability and Stochastic Processes (機率與隨機程序)",
    author: "Roy D. Yates, David J. Goodman",
    edition: "3rd Edition",
    price: 460,
    condition: "Good",
    tags: ["Verified Lender", "Good"],
    department: "Electrical Engineering",
    school: "National Taiwan University",
    professor: "葉丙成 教授",
    location: "台大社科院圖書館 / 椰林大道",
    cover_url: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400",
    owner_id: "owner-ee05",
    owner_name: "丁哲宇",
    owner_avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100",
    owner_rating: 4.8,
    owner_trust_badges: ["快速面交"],
    course_name: "機率與統計",
    course_professor: "葉丙成",
    course_department: "電機工程學系",
    course_semester: "114-1"
  },
  {
    title: "Econometric Analysis (計量經濟學)",
    author: "William H. Greene",
    edition: "8th Edition",
    price: 580,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Economics",
    school: "National Chengchi University",
    professor: "林馨怡 教授",
    location: "政大社會科學大樓 / 商學院大樓",
    cover_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400",
    owner_id: "owner-eco03",
    owner_name: "宋宇航",
    owner_avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
    owner_rating: 4.9,
    owner_trust_badges: ["誠信書主"],
    course_name: "計量經濟學二",
    course_professor: "林馨怡",
    course_department: "經濟學系",
    course_semester: "113-2"
  },
  {
    title: "Statistics for Business and Economics (商務與經濟統計學)",
    author: "David R. Anderson",
    edition: "13th Edition",
    price: 450,
    condition: "Good",
    tags: ["Good"],
    department: "Economics",
    school: "National Chengchi University",
    professor: "郭建華 教授",
    location: "政大指南路麥當勞門口 / 麥側",
    cover_url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400",
    owner_id: "owner-eco04",
    owner_name: "許佩琪",
    owner_avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    owner_rating: 4.7,
    owner_trust_badges: [],
    course_name: "統計學",
    course_professor: "郭建華",
    course_department: "經濟學系",
    course_semester: "114-1"
  },
  {
    title: "The Great Gatsby (大亨小傳 - 英文原著)",
    author: "F. Scott Fitzgerald",
    edition: "Classic Edition",
    price: 150,
    condition: "Good",
    tags: ["Good"],
    department: "Literature & Arts",
    school: "Soochow University",
    professor: "陳安妮 教授",
    location: "東吳雙溪校區第二教研大樓 / 溪畔咖啡廳",
    cover_url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
    owner_id: "owner-sz05",
    owner_name: "連廷安",
    owner_avatar_url: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=100",
    owner_rating: 4.8,
    owner_trust_badges: ["快速面交"],
    course_name: "英美文學導讀",
    course_professor: "陳安妮",
    course_department: "英文學系",
    course_semester: "114-1"
  },
  {
    title: "Hamlet (莎士比亞古典劇本 - 哈姆雷特)",
    author: "William Shakespeare",
    edition: "Classic Edition",
    price: null,
    condition: "Fair",
    tags: ["Donation", "Fair"],
    department: "Literature & Arts",
    school: "Soochow University",
    professor: "李大衛 教授",
    location: "東吳雙溪臨溪路門口 / 自修室",
    cover_url: "https://images.unsplash.com/photo-1474932430478-367db26836c1?w=400",
    owner_id: "owner-sz06",
    owner_name: "蕭婷萱",
    owner_avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    owner_rating: 4.9,
    owner_trust_badges: ["熱心贈書"],
    course_name: "莎士比亞戲劇研究",
    course_professor: "李大衛",
    course_department: "英文學系",
    course_semester: "113-2"
  },
  {
    title: "Organizational Behavior (組織行為學)",
    author: "Stephen P. Robbins, Timothy A. Judge",
    edition: "17th Edition",
    price: 390,
    condition: "Good",
    tags: ["Good"],
    department: "Economics",
    school: "Fu Jen Catholic University",
    professor: "魏秀珍 教授",
    location: "輔大管理學院 / 羅耀拉大樓",
    cover_url: "https://images.unsplash.com/photo-1552581234-2612b75d8953?w=400",
    owner_id: "owner-fj05",
    owner_name: "黃敬庭",
    owner_avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    owner_rating: 4.5,
    owner_trust_badges: [],
    course_name: "組織行為學",
    course_professor: "魏秀珍",
    course_department: "企業管理學系",
    course_semester: "114-1"
  },
  {
    title: "Financial Accounting (財務會計學)",
    author: "Jerry J. Weygandt",
    edition: "10th Edition",
    price: 450,
    condition: "Like New",
    tags: ["Verified Lender", "Like New"],
    department: "Economics",
    school: "Fu Jen Catholic University",
    professor: "沈大為 教授",
    location: "輔大利瑪竇大樓 / 捷運輔大站 2 號出口",
    cover_url: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=400",
    owner_id: "owner-fj06",
    owner_name: "徐可馨",
    owner_avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    owner_rating: 4.8,
    owner_trust_badges: ["誠信書主"],
    course_name: "初等會計學",
    course_professor: "沈大為",
    course_department: "會計學系",
    course_semester: "114-1"
  },
  {
    title: "Introduction to Art History (藝術史導論)",
    author: "Fred S. Kleiner",
    edition: "15th Edition",
    price: 420,
    condition: "Good",
    tags: ["Good"],
    department: "Literature & Arts",
    school: "Fu Jen Catholic University",
    professor: "連思涵 教授",
    location: "輔大織品學院 / 藝術學院大門",
    cover_url: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400",
    owner_id: "owner-fj07",
    owner_name: "簡嘉瑩",
    owner_avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
    owner_rating: 4.7,
    owner_trust_badges: [],
    course_name: "西洋藝術史",
    course_professor: "連思涵",
    course_department: "應用美術學系",
    course_semester: "114-1"
  }
];

async function seed() {
  console.log("正在開始批次寫入 30 筆高品質臺灣大學教科書至 Supabase...");
  let count = 0;
  
  for (const book of newBooks) {
    const { data, error } = await supabase
      .from("books")
      .insert([
        {
          title: book.title,
          author: book.author,
          edition: book.edition,
          price: book.price,
          condition: book.condition,
          tags: book.tags,
          department: book.department,
          school: book.school,
          professor: book.professor,
          location: book.location,
          cover_url: book.cover_url,
          owner_id: book.owner_id,
          owner_name: book.owner_name,
          owner_avatar_url: book.owner_avatar_url,
          owner_rating: book.owner_rating,
          owner_trust_badges: book.owner_trust_badges,
          course_name: book.course_name,
          course_professor: book.course_professor,
          course_department: book.course_department,
          course_semester: book.course_semester
        }
      ])
      .select();

    if (error) {
      console.error(`新增失敗: "${book.title}"。錯誤訊息：`, error.message);
    } else {
      count++;
      console.log(`[成功] (${count}/30) 已寫入: ${book.title}`);
    }
  }

  console.log(`\n🎉 種子資料處理完畢！成功新增 ${count} 筆資料至 Supabase。`);
  process.exit(0);
}

seed();
